service: community-slack

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLACK_TEAM: ${env:SLACK_TEAM}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    ALLOW_ORIGIN: ${env:ALLOW_ORIGIN}

functions:
  doInvite:
    handler: handler.doInvite
    events:
      - http:
          path: invite
          method: post
          cors:
            origin: ${env:ALLOW_ORIGIN}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
plugins:
  - serverless-stack-output

custom:
  output:
    file: .serverless/output-${opt:stage, self:provider.stage}.json

package:
  exclude:
    - 'node_modules/**'
    - 'docs/**'
    - '*.md'
    - 'LICENSE'
    - '*.sh'
    - '*.env'
    - 'package-lock.json'
    - 'package.json'
    - '.vscode/**'
